
services:
  app:
    build: .
    container_name: todo-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET=my_secret_here
      - NODE_ENV=development
      - PORT=5003
    ports:
      - "5003:5003"
    depends_on:
      - db 
    volumes:
      - .:/app
      - /app/node_modules          # Exclude node_modules from being overwritten
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports: 
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
# Volumes là nơi lưu trữ dữ liệu mà container có thể đọc/ghi vào.
volumes: 
  postgres-data:



